[metadata]
name = navigation
version = 0.1.0
description = Navigation nodes for TidyBot

[options]
packages = find:
install_requires =
    rclpy
    numpy
    scipy

[options.entry_points]
console_scripts =
    astar_navigator = navigation.astar_navigator:main
    frontier_explorer = navigation.frontier_exploration:main
    heading_controller = navigation.heading_controller:main
    base_state_estimator = navigation.base_state_estimator:main
    trajectory_tracking = navigation.trajectory_tracking:main
    our_trajectory_tracking = navigation.our_trajectory_tracking:main
